### ISSUE TITLE
Cargo test with the option 'include-ignored' yields error

### ISSUE THREAD

**Issue by arucil** [rust-lang/libtest#21]
I'm using a nightly compiler (by running `rustup install nightly && rustup default nightly`) and ran the following testing command,
```
cargo test -- --include-ignored
```
This command yields the error
```
error: The "include-ignored" flag is only accepted on the nightly compiler
```
I have also tried adding the `+nightly` option, that didn't work either.

The version of the compiler I'm using is
```
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.39.0-nightly (6ef275e6c 2019-09-24)
```

**Comment by pragmatrix** [comment]
Try `cargo test -- -Z unstable-options --include-ignored`.

**Comment by arucil** [comment]
> Try `cargo test -- -Z unstable-options --include-ignored`.

@pragmatrix That solved my problem, thank you !
